In [10]:
import numpy as np
import cv2


ModuleNotFoundError: No module named 'cv2'

Check numpy version

In [ ]:
print(np.__version__)


In [14]:
a = np.array([[1,2,3],[3,4,5]]) # 2x3
b = np.array([[1,2],[3,4],[5,6]]) # 3x2

print(a@b)
print(a+b)

[[22 28]
 [40 52]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(arr.ndim)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


# Slicing arrays
[start:end:step]

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::-1])

[7 6 5 4 3 2 1]
