In [6]:
import cv2 as cv
import numpy as np

In [10]:
# random image numpy
img = np.random.randint(0,255,size=(8,8,3),dtype=np.uint8)

# imS = cv.resize(img, (800, 800))  
# cv.namedWindow('image', cv.WINDOW_NORMAL)
# cv.imshow("Blue",img)
# cv.resizeWindow('image', 800,800)


# cv.waitKey(0)
print(img)

[[[ 71 238 187]
  [106  69 109]
  [203 162 114]
  [ 66 250 253]
  [239  21  78]
  [209  19 149]
  [205 116   2]
  [165 201 196]]

 [[106  76 129]
  [239 111 169]
  [ 82 219 155]
  [ 34 144  96]
  [ 97 110 106]
  [ 84 220  31]
  [ 80 254  91]
  [218  40 191]]

 [[ 67   4 248]
  [ 82 102  80]
  [ 16 163  32]
  [167 127 239]
  [219 248 136]
  [ 56  49 154]
  [226  92 116]
  [148 207 214]]

 [[ 56 197 107]
  [167 238 229]
  [ 71  64  65]
  [ 93  51 146]
  [203  36 141]
  [ 19 188 148]
  [ 49 227  50]
  [174 178 230]]

 [[ 12 111  36]
  [130  25 168]
  [220  29  41]
  [212 214  60]
  [225  69 193]
  [116  15 246]
  [  0  87   7]
  [199 219  20]]

 [[184 128  31]
  [ 92  70  92]
  [163 230  38]
  [ 40 150 131]
  [144  39 218]
  [175 251 117]
  [149   0 206]
  [  1 179  28]]

 [[224 164   9]
  [ 88 156 190]
  [ 94  51 178]
  [ 30 248 189]
  [116  50  11]
  [ 30 152  44]
  [147  73 119]
  [143 244 106]]

 [[ 28 123 156]
  [219  97 186]
  [199 193 173]
  [174  64 213]
  [174 151 162]
  [204  61

In [2]:
img = cv.imread('image.jpg', cv.rgb)
print(img.shape)
for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        if (img[i][j]==255):
            print(0,end='')
        else:
            print(1,end='')
    print()

(224, 224)
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000